// game_state.h
// Global structure to record all game state.
// This file was automatically generated by Spritely 0.6.8 beta

#ifndef _GAME_STATE_H_
#define _GAME_STATE_H_

#include "sprites.h"
#include "backgrounds.h"
#include "animation.h"

// The objects in our game.
// Only 128 objects (0-127) can be defined at any time.
#define	kObj_Player 0
#define kObj_Opponent 1
#define kObj_Ball 2


// The GameState structure holds all of the global game state information.
typedef struct {
	// The (x,y) location of the player's paddle.
	int xPlayer, yPlayer;

	// The (x,y) location of the opponent's paddle.
	int xOpponent, yOpponent;

	// The (x,y) location of the ball.
	int xBall, yBall;
	
	// The current direction that the ball is moving (-1 or 1)
	int dxBall, dyBall;
} GameState;

extern GameState _gs;

void InitGameState();
void UpdateGameState();

#endif	// _GAME_STATE_H_
